language: groovy

jdk:
  - openjdk11

env:
  - MOZ_HEADLESS=1

addons:
  firefox: "66.0.5"
  chrome: stable
  sonarcloud:
    organization: "thomashan-github"

before_install:
  - export DISPLAY=:0
  - rvm install 2.2.6
  - gem install dropbox-deployment

jobs:
  include:
    - stage: test
      script:
        - xvfb-run ./gradlew --scan -i build jacocoTestReport
    - stage: deploy
      script:
        - xvfb-run ./gradlew --scan -i run

after_failure:
  - ./dropbox-deployment.sh
  - dropbox-deployment
