language: groovy

jdk:
  - openjdk11

env:
  - MOZ_HEADLESS=1

addons:
#  firefox: "83.0"
  chrome: stable
  sonarcloud:
    organization: "thomashan-github"

before_install:
  - export DISPLAY=:0
  - rvm install 2.7.0
  - gem install dropbox-deployment
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

stages:
  - test
  - name: run
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      script:
        - xvfb-run ./gradlew --scan -i build jacocoTestReport
    - stage: run
      script:
        - xvfb-run ./gradlew --scan -i run --args "400-450 3-3"
    - script:
        - xvfb-run ./gradlew --scan -i run --args "450-500 3-3"
    - script:
        - xvfb-run ./gradlew --scan -i run --args "500-550 3-3"
    - script:
        - xvfb-run ./gradlew --scan -i run --args "550-600 3-3"
    - script:
        - xvfb-run ./gradlew --scan -i run --args "600-650 3-3"
    - script:
        - xvfb-run ./gradlew --scan -i run --args "650-700 3-3"
    - script:
        - xvfb-run ./gradlew --scan -i run --args "700-750 3-"

after_failure:
  - ./dropbox-deployment.sh
  - dropbox-deployment
