language: groovy

jdk:
  - openjdk11

addons:
  firefox: "66.0.5"
  chrome: stable
  sonarcloud:
    organization: "thomashan-github"

before_install:
  - rvm install 2.2.6
  - gem install dropbox-deployment

script:
  - ./gradlew --scan build jacocoTestReport

after_failure:
  - ./dropbox-deployment.sh dropbox-deployment
